-- ===============================================
-- 报表订阅表测试数据
-- 执行此脚本添加示例订阅数据
-- ===============================================

-- 确保表存在（如果不存在则先创建）
CREATE TABLE IF NOT EXISTS `report_subscription` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(200) NOT NULL COMMENT '订阅名称',
    `code` VARCHAR(50) COMMENT '订阅编码',
    `report_type` VARCHAR(50) NOT NULL COMMENT '报表类型',
    `frequency` VARCHAR(20) NOT NULL COMMENT '发送频率',
    `channel` VARCHAR(100) NOT NULL COMMENT '推送渠道',
    `recipients` TEXT NOT NULL COMMENT '接收人列表',
    `report_config` TEXT COMMENT '报表配置',
    `schedule_config` TEXT COMMENT '调度配置',
    `notification_channels` TEXT COMMENT '通知渠道',
    `notification_template` TEXT COMMENT '通知模板',
    `cc_recipients` TEXT COMMENT '抄送人列表',
    `last_run_at` DATETIME COMMENT '最后运行时间',
    `last_status` VARCHAR(20) COMMENT '最后运行状态',
    `last_error` TEXT COMMENT '最后错误信息',
    `next_run_at` DATETIME COMMENT '下次运行时间',
    `total_runs` INT DEFAULT 0 COMMENT '累计运行次数',
    `success_runs` INT DEFAULT 0 COMMENT '成功次数',
    `creator` VARCHAR(100) COMMENT '创建人',
    `enabled` INT DEFAULT 1 COMMENT '是否启用',
    `schedule_type` VARCHAR(20) DEFAULT 'fixed' COMMENT '推送时间类型',
    `fixed_time` VARCHAR(10) DEFAULT '09:00' COMMENT '固定推送时间',
    `cron_expression` VARCHAR(100) COMMENT 'Cron表达式',
    `weekdays` VARCHAR(20) COMMENT '推送星期',
    `months` VARCHAR(50) COMMENT '推送月份',
    `month_days` VARCHAR(100) COMMENT '推送日期',
    `timezone` VARCHAR(50) DEFAULT 'Asia/Shanghai' COMMENT '时区',
    `require_approval` INT DEFAULT 0 COMMENT '是否需要审批',
    `approval_status` VARCHAR(20) DEFAULT 'approved' COMMENT '审批状态',
    `approver_id` BIGINT COMMENT '审批人ID',
    `approver_name` VARCHAR(100) COMMENT '审批人姓名',
    `approval_time` DATETIME COMMENT '审批时间',
    `approval_remark` VARCHAR(500) COMMENT '审批备注',
    `source` VARCHAR(20) DEFAULT 'user' COMMENT '订阅来源',
    `sensitivity_level` VARCHAR(20) DEFAULT 'normal' COMMENT '敏感级别',
    `template_id` BIGINT COMMENT '通知模板ID',
    `include_attachment` INT DEFAULT 1 COMMENT '是否包含附件',
    `attachment_type` VARCHAR(20) DEFAULT 'log' COMMENT '附件类型',
    `create_user` BIGINT NOT NULL COMMENT '创建人ID',
    `create_user_name` VARCHAR(100) COMMENT '创建人姓名',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `last_send_time` DATETIME COMMENT '最后发送时间',
    `last_send_status` VARCHAR(20) COMMENT '最后发送状态',
    `success_count` INT DEFAULT 0 COMMENT '发送成功次数',
    `failed_count` INT DEFAULT 0 COMMENT '发送失败次数',
    `update_user` BIGINT COMMENT '更新人ID',
    `update_time` DATETIME COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_create_user` (`create_user`),
    KEY `idx_enabled` (`enabled`),
    KEY `idx_report_type` (`report_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报表订阅配置表';

-- 清空现有数据（可选，取消注释可执行）
-- DELETE FROM `report_subscription`;

-- 插入示例订阅数据
INSERT INTO `report_subscription` (
    `name`, `code`, `report_type`, `frequency`, `channel`, `recipients`,
    `report_config`, `schedule_config`, `notification_channels`, `notification_template`,
    `schedule_type`, `fixed_time`, `weekdays`, `month_days`, `timezone`,
    `enabled`, `approval_status`, `source`, `sensitivity_level`, `include_attachment`, `attachment_type`,
    `create_user`, `create_user_name`, `create_time`, `success_count`, `failed_count`
) VALUES 
(
    '每日任务日报', 
    'SUB_DAILY_001', 
    'daily', 
    'daily', 
    'email', 
    'admin@company.com',
    '{"dimensions":["execCount","successRate"],"chartType":"line"}',
    '{"type":"daily","time":"09:00"}',
    '["email"]',
    '每日RPA任务执行统计报表',
    'fixed', 
    '09:00', 
    '1,2,3,4,5', 
    NULL, 
    'Asia/Shanghai',
    1, 
    'approved', 
    'system', 
    'normal', 
    1, 
    'summary',
    1, 
    '管理员', 
    NOW(), 
    0, 
    0
),
(
    '每周执行汇总', 
    'SUB_WEEKLY_001', 
    'weekly', 
    'weekly', 
    'email,dingtalk', 
    'manager@company.com,team@company.com',
    '{"dimensions":["totalTasks","successRate","avgDuration"],"chartType":"bar"}',
    '{"type":"weekly","weekday":1,"time":"10:00"}',
    '["email","dingtalk"]',
    '每周RPA流程执行汇总报表',
    'fixed', 
    '10:00', 
    '1', 
    NULL, 
    'Asia/Shanghai',
    1, 
    'approved', 
    'system', 
    'normal', 
    1, 
    'full',
    1, 
    '管理员', 
    NOW(), 
    0, 
    0
),
(
    '月度成本分析', 
    'SUB_MONTHLY_001', 
    'monthly', 
    'monthly', 
    'email', 
    'finance@company.com',
    '{"dimensions":["cost","savings","roi"],"chartType":"pie"}',
    '{"type":"monthly","day":1,"time":"08:00"}',
    '["email"]',
    '月度RPA成本效益分析报表',
    'fixed', 
    '08:00', 
    NULL, 
    '1', 
    'Asia/Shanghai',
    1, 
    'approved', 
    'system', 
    'sensitive', 
    1, 
    'full',
    1, 
    '管理员', 
    NOW(), 
    0, 
    0
);

SELECT '报表订阅测试数据添加完成！' AS Result;
